openapi: 3.0.1
info:
  title: CrossEcore OpenAPI
  description: "Generates source code"
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /generate/{project}/{language}/:
    post:
      summary: Returns an index of generated files.
      operationId: index
      parameters:
        - name: project
          in: path
          description: file
          required: true
          schema:
            type: string
            format: uuid
        - name: language
          in: path
          description: file
          required: true
          schema:
            type: string
      requestBody:
          description: Contents of the model file as XMI.
          required: false
          content:
            application/xml:
              schema:
                type: object
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /generate/{project}/{filename}:
    get:
      parameters:
        - name: project
          in: path
          description: uuid of the project.
          required: true
          schema:
            type: string
            format: uuid        
        - name: filename
          in: path
          description: name of an generated file.
          required: true
          schema:
            type: string
      responses:
        200:
          description: contents of the file.
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Project:
      type: object
      properties:
        uuid: 
          type: string
          format: uuid
        files:
          type: array
          items:
            $ref: '#/components/schemas/Directory'
    Directory:
      type: object
      properties:
        name:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/Directory'